// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApiTest.Data;

#nullable disable

namespace StoreApiTest.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20250221112138_MoreSeedData")]
    partial class MoreSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bussiness.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Guanajuato",
                            LastName = "Gerardo",
                            Name = "Jorguito"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Monterrey",
                            LastName = "Lopez",
                            Name = "Lucrecia"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Guadalajara",
                            LastName = "Urias",
                            Name = "Samuel"
                        });
                });

            modelBuilder.Entity("Bussiness.Models.CustomerProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("CustomerProducts");
                });

            modelBuilder.Entity("Bussiness.Models.InventaryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quatity")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Bussiness.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Playera para hombre talla mediana en color negro",
                            Image = "https://i.imgur.com/QkIa5tT.jpeg",
                            Price = 700f,
                            Title = "Playera negra"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sudadera muy padre en color gris para hombres con frío",
                            Image = "https://i.imgur.com/wbIMMme.jpeg",
                            Price = 632f,
                            Title = "Sudadera"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sudadera muy padre en color gris oscuro para hombres que tengan frío",
                            Image = "https://i.imgur.com/R2PN9Wq.jpeg",
                            Price = 234f,
                            Title = "Sudadera dark gray"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Es la misma sudadera solo que con otra foto y vendida como otro producto",
                            Image = "https://i.imgur.com/R2PN9Wq.jpeg",
                            Price = 234f,
                            Title = "Sudadera gris gray"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Es una sudadera de color negro muuuuy bonita",
                            Image = "https://i.imgur.com/R2PN9Wq.jpeg",
                            Price = 879f,
                            Title = "Sudadera negra"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Es un pantalón que parece pijama",
                            Image = "https://i.imgur.com/R2PN9Wq.jpeg",
                            Price = 879f,
                            Title = "Pantalón de pijama"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Es un pantalón que parece pijama pero esta vez es para mujeres",
                            Image = "https://i.imgur.com/mp3rUty.jpeg",
                            Price = 373f,
                            Title = "Pijama mujer"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Es un pantalón negro de pijama para caballero",
                            Image = "https://i.imgur.com/ZKGofuB.jpeg",
                            Price = 373f,
                            Title = "Pijama negra"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Es un pantalón blanco de pijama para dama",
                            Image = "https://i.imgur.com/mp3rUty.jpeg",
                            Price = 723f,
                            Title = "Pijama blanca"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Son unos tenis brillantes muy bonitos",
                            Image = "https://i.imgur.com/qNOjJje.jpeg",
                            Price = 2300f,
                            Title = "Tenis para futbool"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Es un sofa muy comodo para cuando te visite la familia",
                            Image = "https://i.imgur.com/Qphac99.jpeg",
                            Price = 5600f,
                            Title = "Sofa negro"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Es el nuevo Iphone con un chip A19 Bionic",
                            Image = "https://m.media-amazon.com/images/I/71ZzBv49bTL.jpg",
                            Price = 28000f,
                            Title = "Iphone 17 Pro Max Plus"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Es un gorro con cordones",
                            Image = "https://i.imgur.com/kg1ZhhH.jpeg",
                            Price = 599f,
                            Title = "Gorro rojo"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Es un vaso de cristal con una naranja dentro",
                            Image = "https://i.imgur.com/b7trwCv.jpeg",
                            Price = 246f,
                            Title = "Vaso de cristal"
                        },
                        new
                        {
                            Id = 15,
                            Description = "No es un control del polystation pero suena bien",
                            Image = "https://i.imgur.com/ZANVnHE.jpeg",
                            Price = 333f,
                            Title = "Polystation Controller"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Deliciosa bebida de fruta fresca",
                            Image = "https://i.imgur.com/BLDByXP.jpeg",
                            Price = 199f,
                            Title = "Jugo de fruta"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Sudadera tipo cholo de barrio, ni el Brayan se te acercará",
                            Image = "https://iili.io/dAyUpkJ.jpg",
                            Price = 399f,
                            Title = "Sudadera roja"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Vasos para tomar agua cuando tengas mucha sed",
                            Image = "https://i.imgur.com/TF0pXdL.jpeg",
                            Price = 799f,
                            Title = "Vasos de cristal"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Perfecto conjunto para cuando te disfraces de santa",
                            Image = "https://i.imgur.com/FDwQgLy.jpeg",
                            Price = 333f,
                            Title = "Sudadera roja"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Ideal para protegerte del sol con estilo.",
                            Image = "https://i.imgur.com/N1GkCIR.jpeg",
                            Price = 150f,
                            Title = "Gorra de color Azul"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Perfecta para días casuales y relajados.",
                            Image = "https://i.imgur.com/cBuLvBi.jpeg",
                            Price = 200f,
                            Title = "Camiseta de color Verde"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Abrígate con comodidad y un toque moderno.",
                            Image = "https://i.imgur.com/KcT6BE0.jpeg",
                            Price = 350f,
                            Title = "Sudadera de color Gris"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Versátil y cómodo para cualquier ocasión.",
                            Image = "https://i.imgur.com/BZrIEmb.jpeg",
                            Price = 400f,
                            Title = "Pantalón de color Negro"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Para mantenerte abrigado con un toque llamativo.",
                            Image = "https://i.imgur.com/wXuQ7bm.jpeg",
                            Price = 550f,
                            Title = "Chamarra de color Rojo"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Accesorio ideal para el invierno.",
                            Image = "https://i.imgur.com/76HAxcA.jpeg",
                            Price = 120f,
                            Title = "Bufanda de color Morado"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Perfecto para un look veraniego.",
                            Image = "https://i.imgur.com/Wv2KTsf.jpeg",
                            Price = 180f,
                            Title = "Sombrero de color Beige"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Comodidad y estilo en cada paso.",
                            Image = "https://i.imgur.com/R3iobJA.jpeg",
                            Price = 600f,
                            Title = "Zapatos de color Marrón"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Ideal para darle vida a tu outfit.",
                            Image = "https://i.imgur.com/JQRGIc2.jpeg",
                            Price = 300f,
                            Title = "Suéter de color Amarillo"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Añade una capa extra de calidez y estilo.",
                            Image = "https://i.imgur.com/mp3rUty.jpeg",
                            Price = 250f,
                            Title = "Chaleco de color Naranja"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Fresca y ligera para el verano.",
                            Image = "https://i.imgur.com/N1GkCIR.jpeg",
                            Price = 220f,
                            Title = "Playera de color Celeste"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Comodidad y frescura para días calurosos.",
                            Image = "https://i.imgur.com/cBuLvBi.jpeg",
                            Price = 280f,
                            Title = "Pantalones cortos de color Caqui"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Combina con cualquier atuendo casual.",
                            Image = "https://i.imgur.com/KcT6BE0.jpeg",
                            Price = 130f,
                            Title = "Gorra de color Blanco"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Perfecto para climas frescos con estilo.",
                            Image = "https://i.imgur.com/BZrIEmb.jpeg",
                            Price = 370f,
                            Title = "Jersey de color Vino"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Ideal para aventuras al aire libre.",
                            Image = "https://i.imgur.com/wXuQ7bm.jpeg",
                            Price = 600f,
                            Title = "Cazadora de color Verde Oliva"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Dale un toque de color vibrante a tu look.",
                            Image = "https://i.imgur.com/76HAxcA.jpeg",
                            Price = 250f,
                            Title = "Blusa de color Fucsia"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Aporta calidez sin perder movilidad.",
                            Image = "https://i.imgur.com/Wv2KTsf.jpeg",
                            Price = 320f,
                            Title = "Chaleco de color Gris Oscuro"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Estilo y comodidad en cada pisada.",
                            Image = "https://i.imgur.com/R3iobJA.jpeg",
                            Price = 700f,
                            Title = "Botines de color Caramelo"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Alegra tu día con este color enérgico.",
                            Image = "https://i.imgur.com/JQRGIc2.jpeg",
                            Price = 210f,
                            Title = "Camiseta de color Naranja"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Perfecta para mantenerte abrigado y cómodo.",
                            Image = "https://i.imgur.com/mp3rUty.jpeg",
                            Price = 350f,
                            Title = "Sudadera de color Azul Marino"
                        },
                        new
                        {
                            Id = 40,
                            Description = "El toque ideal para un look invernal.",
                            Image = "https://i.imgur.com/N1GkCIR.jpeg",
                            Price = 140f,
                            Title = "Bufanda de color Azul Cobalto"
                        });
                });

            modelBuilder.Entity("Bussiness.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sucursal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Bussiness.Models.StoreInventary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("StoreInventary", (string)null);
                });

            modelBuilder.Entity("Bussiness.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Email = "jorguito@example.com",
                            HashPassword = "b88b88cd87cf54d08aabf61b73023cf35551850dc8da5a9d8ae410ef243f74ce",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            Email = "lucrecia@example.com",
                            HashPassword = "362b3c03a6b7ad6e47e3029b1eb9f31194123825ff4aec5833feca5e120446f0",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            Email = "samueljuan@example.com",
                            HashPassword = "67a0978030e50d8f060cc216bc9ae8ea0e3fa38f0951cc412e5b41744f548add",
                            Role = 0
                        });
                });

            modelBuilder.Entity("Bussiness.Models.CustomerProduct", b =>
                {
                    b.HasOne("Bussiness.Models.Customer", "Customer")
                        .WithMany("CartProducts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bussiness.Models.InventaryTransaction", b =>
                {
                    b.HasOne("Bussiness.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness.Models.StoreInventary", "StoreStock")
                        .WithMany("Transacctions")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");

                    b.Navigation("StoreStock");
                });

            modelBuilder.Entity("Bussiness.Models.StoreInventary", b =>
                {
                    b.HasOne("Bussiness.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness.Models.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Bussiness.Models.User", b =>
                {
                    b.HasOne("Bussiness.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Bussiness.Models.Customer", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("Bussiness.Models.Store", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Bussiness.Models.StoreInventary", b =>
                {
                    b.Navigation("Transacctions");
                });
#pragma warning restore 612, 618
        }
    }
}
